apiVersion: v1
kind: Pod
metadata:
  name: opa-allowed
spec:
  containers:
  - name: opa
    image: openpolicyagent/opa:0.9.2
    args:
      - "run"
      - "--server"
      - "--addr=localhost:8080"
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
