apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission-control
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://glaciation-heu.github.io/security/helm-charts'
    chart: admission-control
    targetRevision: 1.0.*
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
