apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-wrapping
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://glaciation-heu.github.io/security/dev'
    chart: data-wrapping
    targetRevision: 1.0.*
    helm:
      valuesObject:
        tenant:
          tenant:
            pools:
            - name: pool
              # Number of MinIO Tenant pods
              servers: 2
              # Number of volumes per MinIO Tenant pod
              volumesPerServer: 2
              # Size of each volume
              size: 1Gi
              # Storage class of the volumes
              storageClassName: local-path
              # Minimum and maximum resources requested for each pod
              resources:
                requests:
                  cpu: 1
                  memory: 2Gi
                limits:
                  cpu: 2
                  memory: 4Gi
              # Security context of the pods
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
                fsGroupChangePolicy: "OnRootMismatch"
                runAsNonRoot: true
              # Security context of the containers
              containerSecurityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
          ingress:
            api:
              enabled: true
              ingressClassName: "nginx"
              annotations:
                # NOTE: To make sure the certificate is trusted by clients we should use
                # something like Let's Encrypt
                cert-manager.io/cluster-issuer: "private-ca-issuer"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                nginx.ingress.kubernetes.io/proxy-body-size: 1g
              tls:
              - hosts:
                - glaciation-tenant.integration
                secretName: minio-tenant-ingress
              host: glaciation-tenant.integration
              path: /
              pathType: Prefix
            console:
              enabled: true
              ingressClassName: "nginx"
              annotations:
                # NOTE: To make sure the certificate is trusted by clients we should use
                # something like Let's Encrypt
                cert-manager.io/cluster-issuer: "private-ca-issuer"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
                nginx.ingress.kubernetes.io/proxy-body-size: 1g
              tls:
              - hosts:
                - glaciation-tenant-console.integration
                secretName: minio-tenant-console-ingress
              host: glaciation-tenant-console.integration
              path: /
              pathType: Prefix
        vault:
          server:
            dataStorage:
              size: 1Gi
              storageClass: local-path
            auditStorage:
              size: 1Gi
              storageClass: local-path
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                # NOTE: To make sure the certificate is trusted by clients we should use
                # something like Let's Encrypt
                cert-manager.io/cluster-issuer: "private-ca-issuer"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              tls:
              - hosts:
                - vault.integration
                secretName: vault-ingress
              hosts:
              - host: vault.integration
              activeService: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data-wrapping
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
