apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-wrapping
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://glaciation-heu.github.io/security/dev'
    chart: data-wrapping
    targetRevision: 1.0.*
    helm:
      valuesObject:
        tenant:
          ingress:
            api:
              enabled: true
              ingressClassName: "nginx"
              annotations:
                # NOTE: To make sure the certificate is trusted by clients we should use
                # something like Let's Encrypt
                cert-manager.io/cluster-issuer: "private-ca-issuer"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              tls:
              - hosts:
                - glaciation-tenant.integration
                secretName: minio-tenant-ingress
              host: glaciation-tenant.integration
              path: /
              pathType: Prefix
            console:
              enabled: true
              ingressClassName: "nginx"
              annotations:
                # NOTE: To make sure the certificate is trusted by clients we should use
                # something like Let's Encrypt
                cert-manager.io/cluster-issuer: "private-ca-issuer"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              tls:
              - hosts:
                - glaciation-tenant-console.integration
                secretName: minio-tenant-console-ingress
              host: glaciation-tenant-console.integration
              path: /
              pathType: Prefix
        vault:
          server:
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                # NOTE: To make sure the certificate is trusted by clients we should use
                # something like Let's Encrypt
                cert-manager.io/cluster-issuer: "private-ca-issuer"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              tls:
              - hosts:
                - vault.integration
                secretName: vault-ingress
              hosts:
              - host: vault.integration
              activeService: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data-wrapping
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
