apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-sanitization
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://glaciation-heu.github.io/data-sanitization-service
    chart: data-sanitization
    targetRevision: 0.2.2
    helm:
      valueFiles:
      - $values/values/data-sanitization-values.yaml
  - repoURL: 'https://github.com/unibg-seclab/glaciation-gitops-test.git'
    targetRevision: http
    ref: values
  destination:
    namespace: spark-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
