apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-wrapping
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://glaciation-heu.github.io/security/helm-charts'
    chart: data-wrapping
    targetRevision: 1.0.*
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data-wrapping
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
