apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policy-manager
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gpm
    repoURL: https://sighupio.github.io/gatekeeper-policy-manager
    targetRevision: 0.10.0
    helm:
      parameters:
        - name: service.type
          value: NodePort
        - name: config.secretKey
          value: supersecuresecretkey
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
