apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policy-manager
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: gatekeeper-policy-manager
    repoURL: https://sighupio.github.io/gatekeeper-policy-manager
    targetRevision: 0.10.0
    helm:
      valuesObject:
        config:
          secretKey: supersecuresecretkey
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            # NOTE: To make sure the certificate is trusted by clients we should use
            # something like Let's Encrypt
            cert-manager.io/cluster-issuer: "private-ca-issuer"
          tls:
          - hosts:
            - gpm.integration
            secretName: gpm-ingress
          hosts:
          - host: gpm.integration
            paths:
            - /
            pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
