apiVersion: v1
kind: Namespace
metadata:
  name: minio-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    create-ca-bundle: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-kes
  namespace: minio-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: minio-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: minio-kes
  namespace: minio-tenant
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kes-secret
  namespace: minio-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    kubernetes.io/service-account.name: minio-kes
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "vault"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kes-secret
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    replicator.v1.mittwald.de/replicate-from: minio-tenant/minio-kes-secret
data: {}
