apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://operator.min.io
    chart: operator
    targetRevision: 5.0.14
    helm:
      valuesObject:
        console:
          ingress:
            enabled: false
          # The ingress is not working well in our *no balancer setup* with fixed ingress controller IP
          #   ingressClassName: "nginx"
          #   host: minio-console.integration
          #   path: /
          #   pathType: Prefix
        tenants: []
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
