apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://operator.min.io
    chart: tenant
    targetRevision: 5.0.14
    helm:
      valueFiles:
      - $values/values/minio-tenant-values.yaml
  - repoURL: 'https://github.com/unibg-seclab/glaciation-gitops-test.git'
    targetRevision: http
    ref: values
  destination:
    namespace: minio-tenant
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
