apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-uc1-tenant-node-selector
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-10"
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    namespaces: ["mef-sog-uc1-wl"]
  location: spec.nodeSelector.uc1-tenant
  parameters:
    pathTests:
    - subPath: spec.nodeSelector.uc1-tenant
      condition: MustNotExist
    assign:
      value: "true"
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: add-uc2-tenant-node-selector
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-10"
spec:
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  match:
    namespaces: ["uc2"]
  location: spec.nodeSelector.uc2-tenant
  parameters:
    pathTests:
    - subPath: spec.nodeSelector.uc2-tenant
      condition: MustNotExist
    assign:
      value: "true"
