apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-history-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://glaciation-heu.github.io/spark-history-server
    chart: spark-history-server
    targetRevision: 1.0.3
    helm:
      valueFiles:
      - $values/values/spark-history-server-values.yaml
  - repoURL: 'https://github.com/unibg-seclab/glaciation-gitops-test.git'
    targetRevision: http
    ref: values
  destination:
    namespace: spark-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
