apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: trust-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v0.9.2
    helm:
      valuesObject:
        podDisruptionBudget:
          enabled: true
        replicaCount: 2
        secretTargets:
          enabled: true
          authorizedSecrets:
          - ca-bundle
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
