apiVersion: v1
kind: Namespace
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    create-ca-bundle: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: vault-tls
  issuerRef:
    name: private-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
  subject:
    organizations:
      - system:nodes
  commonName: system:node:*.vault.svc.cluster.local
  isCA: false
  # TODO: Try restricting usages to digital signature, key encipherment, and
  # server auth
  usages:
  - digital signature
  - key encipherment
  - data encipherment
  - server auth
  - client auth
  dnsNames:
  - "*.vault-internal"
  - "*.vault-internal.vault.svc.cluster.local"
  - "*.vault"
  - "vault-internal.vault.svc.cluster.local"
  ipAddresses:
  - 127.0.0.1
  - 192.168.49.2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      valueFiles:
      - $values/values/vault-ha-values.yaml
  - repoURL: 'https://github.com/unibg-seclab/glaciation-gitops-test.git'
    targetRevision: http
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kes-policy
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  kes-policy.hcl: |
    path "kv/data/minio-tenant/*" {
      capabilities = [ "create", "read" ]
    }
    path "kv/metadata/minio-tenant/*" {
      capabilities = [ "list", "delete" ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-unseal-vault-cluster
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-unseal-vault-cluster
  template:
    metadata:
      labels:
        app: auto-unseal-vault-cluster
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.16.1
        env:
        - name: "SHARES"
          value: "5"
        - name: "THRESHOLD"
          value: "3"
        command:
        - /bin/sh
        - -c
        - |
          set -e # make sure the service fails if any instruction fails

          function unseal {
              head -n $THRESHOLD /vault/cluster-keys |
              while read line; do
                vault operator unseal \
                  -address=https://$1.vault-internal:8200 \
                  $line;
              done
          }

          echo '[*] Initialize HA Vault cluster'
          
          # Loop infinitely
          while :
          do
              # Wait for the startup of the Vault pods / delay before next
              # status check
              sleep 30 # it does the job without requiring to create an ad hoc image

              if ! vault operator init -address=https://vault-0.vault-internal:8200 -status; then
                  # Setup HA Vault cluster leader
                  # TODO: Persist PGP encrypted Vault unseal keys somewhere outside the cluster
                  vault operator init \
                    -address=https://vault-0.vault-internal:8200 \
                    -key-shares=$SHARES \
                    -key-threshold=$THRESHOLD \
                    -format=json > /vault/response.json

                  # Extract unseal keys from the JSON response
                  awk '/"unseal_keys_b64": \[/{flag=1;next}/\]/{flag=0}flag' /vault/response.json | sed -n 's/\s*"\(.*\)".*/\1/p' > /vault/cluster-keys
              fi

              unseal vault-0

              # Setup HA Vault cluster follower (vault-1)
              vault operator raft join \
                -address=https://vault-1.vault-internal:8200 \
                -leader-ca-cert="$(cat /vault/userconfig/vault-tls/ca.crt)" \
                -leader-client-cert="$(cat /vault/userconfig/vault-tls/tls.crt)" \
                -leader-client-key="$(cat /vault/userconfig/vault-tls/tls.key)" \
                https://vault-0.vault-internal:8200
              unseal vault-1

              # Setup HA Vault cluster follower (vault-2)
              vault operator raft join \
                -address=https://vault-2.vault-internal:8200 \
                -leader-ca-cert="$(cat /vault/userconfig/vault-tls/ca.crt)" \
                -leader-client-cert="$(cat /vault/userconfig/vault-tls/tls.crt)" \
                -leader-client-key="$(cat /vault/userconfig/vault-tls/tls.key)" \
                https://vault-0.vault-internal:8200
              unseal vault-2

              echo -e '\n[*] Setup HA Vault cluster for integration with MinIO'
              VAULT_ROOT_TOKEN=$(sed -n 's/\s*"root_token": "\(.*\)".*/\1/p' /vault/response.json)
              vault login \
                -address=https://vault-0.vault-internal:8200 \
                $VAULT_ROOT_TOKEN
              vault secrets enable \
                -address=https://vault-0.vault-internal:8200 \
                -version=2 \
                kv
              vault policy write \
                -address=https://vault-0.vault-internal:8200 \
                kes-policy /minio/kes/kes-policy.hcl
              vault auth enable \
                -address=https://vault-0.vault-internal:8200 \
                kubernetes
              vault write \
                -address=https://vault-0.vault-internal:8200 \
                auth/kubernetes/config \
                token_reviewer_jwt="$(cat /minio/kes/service-account/token)" \
                kubernetes_host="https://kubernetes.default.svc.cluster.local" \
                kubernetes_ca_cert="$(cat /minio/kes/service-account/ca.crt)" \
                issuer="https://kubernetes.default.svc.cluster.local"
              vault write \
                -address=https://vault-0.vault-internal:8200 \
                auth/kubernetes/role/minio-kes \
                bound_service_account_names=minio-kes \
                bound_service_account_namespaces=minio-tenant \
                policies=kes-policy \
                ttl=1h
          done
        securityContext:
          runAsUser: 100
          runAsGroup: 1000
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
          name: ca-bundle
          readOnly: true
        - mountPath: /vault/userconfig/vault-tls
          name: userconfig-vault-tls
          readOnly: true
        - mountPath: /minio/kes/service-account
          name: minio-kes-service-account-token
          readOnly: true
        - mountPath: /minio/kes/kes-policy.hcl
          subPath: kes-policy.hcl
          name: kes-policy
          readOnly: true
      restartPolicy: Always
      securityContext:
        runAsUser: 100
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: ca-bundle
        configMap:
          defaultMode: 422
          name: ca-bundle
      - name: userconfig-vault-tls
        secret:
          defaultMode: 420
          secretName: vault-tls
      - name: minio-kes-service-account-token
        secret:
          defaultMode: 420
          secretName: minio-kes-secret
      - name: kes-policy
        configMap:
          defaultMode: 420
          name: kes-policy
